server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPRSTUVWXYZ
spring:
  security:
    user:
      name: emrullahyz
      password: 12345
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/EmrullahYz/microservices-with-spring-cloud-config-wa-tolls
          search-paths:
            - station*
          repos:
            perf:
              pattern: "*/perf"
              uri: https://github.com/EmrullahYz/microservices-with-spring-cloud-config-wa-tolls-perf
              search-paths:
                - station*
